site_name: 'python-app-111'
site_description: 'Main documentation for python-app-111'

repo_url: https://github.com/alipendix/python-app-111
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting Started: index.md